### ISSUE TITLE
피해보상

### ISSUE THREAD

**Issue by KimDarren** [devholic/honeyjam#5]
이 Repository 때문에 제 배꼽을 잃어버렸습니다...
피해보상은 누가 해주죠?ㅠㅠ 배꼽이 돌아오질 않습니다.

**Comment by devholic** [comment]
[가까운 병원](http://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&ie=utf8&query=%EB%B3%91%EC%9B%90)에 가십쇼. 
촤하하하!
